services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        MAX_MEMORY: ${MAX_MEMORY}
    image: ${APP_NAME}-${NODE_ENV}:latest
    restart: unless-stopped
    ports:
      - ${APP_PORT}:${APP_PORT}
    # volumes:
    #   # Mounting the entire project root for hot-reloading in development (excluding what's in .dockerignore): only for development environment
    #   - .:/app:delegated
    #   # Prevent overwriting node_modules in container
    #   - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "${BACKEND_MAIN_URL}/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: ${MAX_MEMORY}M
        reservations:
          memory: ${MIN_MEMORY}M
    networks:
      - scholar-network

networks:
  scholar-network:
    name: scholar-network
    driver: bridge